@startuml
skinparam Monochrome true

start

:Read application list from XML file;

:Press and hold an application;

:Application status change to PRESS;

while (Hold)
:Move app to left / right direction;
:Other app at corresponding shift in other direction;
:Save application to XML File;
endwhile (release)

:Release application;

:Application status change to FOCUS;



stop

@enduml