@startuml
skinparam Monochrome true

package HomeApplication {
  [View (QML)] as view

  [Model (C++)] as model

  [Controller (C++)] as con

  view -- model

  model -- con
}


package ClimateService {
  [Climate Service] as cli
}


() DBus as dbus

con - dbus

dbus - cli



@enduml