@startuml
skinparam Monochrome true

start
:Load Applications;
if (Number of applications > 6) then (yes)
:Show scroll bar;
:Flick scroll bar;
:Application view move in corresponding position;
else (no)
:Hide scroll bar;
endif
:Update Application ListView;

stop

@enduml